defmodule Mix.Tasks.Duskmoon.Bundle do
  @moduledoc """
  Pre-bundle @duskmoon-dev/elements for Volt dev server.

  Volt's vendor prebundler cannot bundle @duskmoon-dev elements in umbrella
  projects because OXC sets the bundle cwd to the package's parent directory,
  which prevents resolving sibling scoped packages (@duskmoon-dev/el-base,
  @duskmoon-dev/core, etc.).

  This task uses OXC directly with the project root as cwd, then writes the
  bundled output to assets/js/ where Volt can serve it as a regular source file.

  ## Usage

      mix duskmoon.bundle                    # Bundle all elements
      mix duskmoon.bundle el-button el-table # Bundle specific elements
  """

  use Mix.Task

  @shortdoc "Pre-bundle @duskmoon-dev/elements for Volt"

  # Keep this list to custom elements rendered by sigma_web. Volt/OXC can get
  # killed by the full DuskMoon element graph, while Bun previously tolerated it.
  # Elements with dynamic imports (el-markdown-input, el-chat) or large markdown
  # dependency graphs are prebundled separately with Bun.
  @all_elements ~w(
    el-autocomplete el-button el-card el-chip el-dialog el-menu el-popover
  )

  @rich_elements ~w(el-chat el-markdown el-markdown-input)

  @impl Mix.Task
  def run(args) do
    paths = paths()

    try do
      do_run(args, paths)
    after
      File.rm_rf(paths.tmp_dir)
    end
  end

  defp do_run(args, paths) do
    elements = if args == [], do: @all_elements, else: args

    %{
      node_modules: node_modules_path,
      output: output_path,
      rich_output: rich_output_path,
      tmp_dir: tmp_dir
    } = paths

    Mix.shell().info("Bundling #{length(elements)} @duskmoon-dev element(s)...")

    imports =
      Enum.map_join(elements, "\n", fn el ->
        "import '@duskmoon-dev/#{el}/register';"
      end)

    # OXC requires the entry file to live inside cwd
    File.mkdir_p!(tmp_dir)
    entry = Path.join(tmp_dir, "entry.js")
    File.write!(entry, imports)

    case OXC.bundle(entry,
           cwd: File.cwd!(),
           format: :esm,
           modules: [node_modules_path],
           define: %{"process.env.NODE_ENV" => ~s("development")},
           exports: :named,
           preserve_entry_signatures: :strict
         ) do
      {:ok, %{code: code}} -> write_output(output_path, code, elements)
      {:ok, code} when is_binary(code) -> write_output(output_path, code, elements)
      {:error, errors} -> Mix.raise("Failed to bundle elements: #{inspect(errors)}")
    end

    bundle_rich_elements(tmp_dir, rich_output_path)
  end

  defp paths do
    cwd = File.cwd!()

    web_root =
      if String.ends_with?(cwd, "apps/sigma_web"), do: cwd, else: Path.join(cwd, "apps/sigma_web")

    %{
      node_modules: Path.join(web_root, "node_modules"),
      output: Path.join(web_root, "assets/js/duskmoon_elements.js"),
      rich_output: Path.join(web_root, "priv/static/assets/js/duskmoon_rich_elements.js"),
      tmp_dir: Path.join(web_root, "_build/duskmoon_bundle")
    }
  end

  defp write_output(output_path, code, elements) do
    header = """
    /**
     * Pre-bundled @duskmoon-dev/elements (generated by mix duskmoon.bundle)
     *
     * Elements: #{Enum.join(elements, ", ")}
     *
     * DO NOT EDIT — regenerate with: mix duskmoon.bundle #{Enum.join(elements, " ")}
     */
    """

    File.mkdir_p!(Path.dirname(output_path))
    File.write!(output_path, header <> code)
    size_kb = (byte_size(code) / 1024) |> Float.round(1)
    Mix.shell().info("Wrote #{output_path} (#{size_kb} KB, #{length(elements)} element(s))")
  end

  defp bundle_rich_elements(tmp_dir, output_path) do
    bun =
      System.find_executable("bun") ||
        Mix.raise("bun is required to bundle DuskMoon rich elements")

    entry = Path.join(tmp_dir, "rich_elements.js")

    imports =
      Enum.map_join(@rich_elements, "\n", fn el ->
        "import '@duskmoon-dev/#{el}/register';"
      end)

    File.write!(entry, imports <> "\n")
    File.mkdir_p!(Path.dirname(output_path))

    args = [
      "build",
      entry,
      "--bundle",
      "--format=esm",
      "--minify",
      "--target=browser",
      "--outfile=#{output_path}"
    ]

    Mix.shell().info("Bundling #{length(@rich_elements)} rich DuskMoon element(s) with Bun...")

    case System.cmd(bun, args, stderr_to_stdout: true) do
      {output, 0} ->
        unless String.trim(output) == "", do: Mix.shell().info(output)

      {output, status} ->
        Mix.raise("Failed to bundle rich DuskMoon elements with Bun (#{status}):\n#{output}")
    end
  end
end
