defmodule Mix.Tasks.Duskmoon.Bundle do
  @moduledoc """
  Pre-bundle @duskmoon-dev/elements for Volt dev server.

  Volt's vendor prebundler cannot bundle @duskmoon-dev elements in umbrella
  projects because OXC sets the bundle cwd to the package's parent directory,
  which prevents resolving sibling scoped packages (@duskmoon-dev/el-base,
  @duskmoon-dev/core, etc.).

  This task uses OXC directly with the project root as cwd, then writes the
  bundled output to assets/js/ where Volt can serve it as a regular source file.

  ## Usage

      mix duskmoon.bundle                    # Bundle all elements
      mix duskmoon.bundle el-button el-table # Bundle specific elements
  """

  use Mix.Task

  @shortdoc "Pre-bundle @duskmoon-dev/elements for Volt"

  # Elements with dynamic imports (el-markdown, el-code-engine, el-markdown-input,
  # el-chat) are excluded — OXC cannot bundle them into a single file.
  @all_elements ~w(
    el-accordion el-alert el-autocomplete el-badge el-bottom-navigation
    el-bottom-sheet el-breadcrumbs el-button el-card el-cascader el-chart
    el-chip el-circle-menu el-code-block el-datepicker el-dialog
    el-drawer el-file-upload el-form el-form-group el-input
    el-menu el-navbar el-navigation el-nested-menu el-otp-input el-pagination
    el-pin-input el-popover el-progress el-segment-control el-select el-slider
    el-stepper el-switch el-table el-tabs el-theme-controller el-time-input
    el-tooltip
  )

  @impl Mix.Task
  def run(args) do
    elements = if args == [], do: @all_elements, else: args
    %{node_modules: node_modules_path, output: output_path} = paths()

    Mix.shell().info("Bundling #{length(elements)} @duskmoon-dev element(s)...")

    imports =
      Enum.map_join(elements, "\n", fn el ->
        "import '@duskmoon-dev/#{el}/register';"
      end)

    # OXC requires the entry file to live inside cwd
    tmp_dir = Path.join(File.cwd!(), "_build/duskmoon_bundle")
    File.mkdir_p!(tmp_dir)
    entry = Path.join(tmp_dir, "entry.js")
    File.write!(entry, imports)

    case OXC.bundle(entry,
           cwd: File.cwd!(),
           format: :esm,
           modules: [node_modules_path],
           define: %{"process.env.NODE_ENV" => ~s("development")},
           exports: :named,
           preserve_entry_signatures: :strict
         ) do
      {:ok, %{code: code}} -> write_output(output_path, code, elements)
      {:ok, code} when is_binary(code) -> write_output(output_path, code, elements)
      {:error, errors} -> Mix.raise("Failed to bundle elements: #{inspect(errors)}")
    end
  after
    File.rm_rf(Path.join(File.cwd!(), "_build/duskmoon_bundle"))
  end

  defp paths do
    cwd = File.cwd!()

    if String.ends_with?(cwd, "apps/ex_pi_web") do
      root = Path.expand("../..", cwd)

      %{
        node_modules: Path.join(root, "node_modules"),
        output: Path.join(cwd, "assets/js/duskmoon_elements.js")
      }
    else
      %{
        node_modules: Path.join(cwd, "node_modules"),
        output: Path.join([cwd, "apps/ex_pi_web", "assets/js/duskmoon_elements.js"])
      }
    end
  end

  defp write_output(output_path, code, elements) do
    header = """
    /**
     * Pre-bundled @duskmoon-dev/elements (generated by mix duskmoon.bundle)
     *
     * Elements: #{Enum.join(elements, ", ")}
     *
     * DO NOT EDIT — regenerate with: mix duskmoon.bundle #{Enum.join(elements, " ")}
     */
    """

    File.mkdir_p!(Path.dirname(output_path))
    File.write!(output_path, header <> code)
    size_kb = (byte_size(code) / 1024) |> Float.round(1)
    Mix.shell().info("Wrote #{output_path} (#{size_kb} KB, #{length(elements)} element(s))")
  end
end
